[build]
builder = "dockerfile"
dockerfilePath = "infra/docker/languagetool.Dockerfile"

[deploy]
healthcheckPath = "/v2/languages"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
